sonar.projectKey=ecored
sonar.projectName=EcoRed
sonar.sources=artifacts/api-server/src,artifacts/ecored/src
sonar.tests=artifacts/api-server/src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,lib/api-client-react/src/generated/**,lib/api-zod/src/generated/**,artifacts/ecored/src/components/ui/**
sonar.javascript.lcov.reportPaths=reports/tests/coverage/lcov.info
sonar.sourceEncoding=UTF-8